"""PowerPoint generation service using AI content."""
import os
import logging
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from groq import Groq
from dotenv import load_dotenv
import json

load_dotenv()
logger = logging.getLogger(__name__)

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def generate_ppt_content(task_description: str) -> dict:
    """Generate PPT content using AI based on task description."""
    prompt = f"""You are a professional presentation creator. Based on this task: "{task_description}"

Create a PowerPoint presentation structure with:
1. Title slide
2. 3-5 content slides with bullet points
3. Conclusion slide

Return ONLY valid JSON in this format:
{{
    "title": "Presentation Title",
    "subtitle": "Brief subtitle",
    "slides": [
        {{
            "title": "Slide Title",
            "content": ["Bullet point 1", "Bullet point 2", "Bullet point 3"]
        }}
    ]
}}"""

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
            max_tokens=1024,
        )
        text = response.choices[0].message.content.strip()
        
        # Clean JSON
        if "```json" in text:
            text = text.split("```json")[1].split("```")[0].strip()
        elif "```" in text:
            text = text.split("```")[1].split("```")[0].strip()
            
        return json.loads(text)
    except Exception as e:
        logger.error(f"PPT content generation failed: {e}")
        return {
            "title": task_description,
            "subtitle": "Auto-generated by MeetingMind AI",
            "slides": [
                {
                    "title": "Overview",
                    "content": ["Task assigned from meeting", "AI-generated content", "Ready for customization"]
                }
            ]
        }

def create_powerpoint(assignee: str, task: str, deadline: str = None) -> str:
    """Create a PowerPoint presentation file."""
    try:
        # Generate AI content
        content = generate_ppt_content(task)
        
        # Create presentation
        prs = Presentation()
        
        # Title slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        title.text = content.get("title", task)
        subtitle_text = f"Assigned to: {assignee}"
        if deadline:
            subtitle_text += f"\nDeadline: {deadline}"
        subtitle_text += f"\n{content.get('subtitle', 'Auto-generated by MeetingMind AI')}"
        subtitle.text = subtitle_text
        
        # Content slides
        for slide_data in content.get("slides", []):
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            
            title = slide.shapes.title
            title.text = slide_data.get("title", "Content")
            
            content_placeholder = slide.placeholders[1]
            tf = content_placeholder.text_frame
            
            for i, bullet in enumerate(slide_data.get("content", [])):
                if i == 0:
                    tf.text = bullet
                else:
                    p = tf.add_paragraph()
                    p.text = bullet
                    p.level = 0
        
        # Conclusion slide
        bullet_slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(bullet_slide_layout)
        title = slide.shapes.title
        title.text = "Next Steps"
        
        content_placeholder = slide.placeholders[1]
        tf = content_placeholder.text_frame
        tf.text = "Review and customize this presentation"
        p = tf.add_paragraph()
        p.text = "Add specific details and data"
        p = tf.add_paragraph()
        p.text = "Present to stakeholders"
        
        # Save file
        filename = f"ppt_{assignee.replace(' ', '_')}_{task[:20].replace(' ', '_')}.pptx"
        filepath = os.path.join("generated_files", filename)
        
        # Create directory if not exists
        os.makedirs("generated_files", exist_ok=True)
        
        prs.save(filepath)
        logger.info(f"PPT created: {filepath}")
        return filepath
        
    except Exception as e:
        logger.error(f"PPT creation failed: {e}")
        return None

def should_generate_ppt(task: str) -> bool:
    """Check if task requires PPT generation."""
    ppt_keywords = [
        "ppt", "powerpoint", "presentation", "slides", "deck",
        "present", "slide", "प्रेजेंटेशन", "स्लाइड"
    ]
    return any(keyword in task.lower() for keyword in ppt_keywords)